### ISSUE TITLE
Issue with content types in browser 

### ISSUE THREAD

**Issue by EON3ILL** [bold-benchmark/bold-server#24]
When querying the RDF in a browser when running the server - received the following error.

java.lang.NullPointerException
	at org.bold.conneg.AcceptedContentTypes$AcceptedContentTypesListener.enterMediaRange(AcceptedContentTypes.java:39)
	at org.bold.conneg.parser.AcceptHeaderParser$MediaRangeContext.enterRule(AcceptHeaderParser.java:200)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.bold.conneg.AcceptedContentTypes.<init>(AcceptedContentTypes.java:74)
	at org.bold.gsp.GraphStoreHandler.handle(GraphStoreHandler.java:62)
	at org.bold.sim.SimulationHandler.handle(SimulationHandler.java:103)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by vcharpenay** [comment]
OK, thanks. Can you also give the exact value of the `Accept` header that is set by your browser?

**Comment by EON3ILL** [comment]
Hey Victor,

The following was obtained by using the following website -
https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending

application/ld+json;q=1,application/n-quads;q=1,application/n-triples;q=1,application/rdf+xml;q=1,application/trig;q=1,text/turtle;q=1,text/n3;q=1,text/html;q=0.95,application/xhtml+xml;q=0.95,application/xml;q=0.85,image/webp;q=0.95,*/*;q=0.75


I hope this is sufficient.

Please let me know if I need to do anything else.

Kind regards,
--
Eoin O'Neill
PhD Researcher, CONSUS Project.

UCD School of Computer Science, College of Science,
University College Dublin, Belfield, Dublin 4, Ireland.

Email: ***@***.***
